name: PyPi sdist

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PLINKIO_PYPI_TOKEN }}
      run: |
        python setup.py sdist
        twine upload dist/*
